### ISSUE TITLE
Merge TLS certs

### ISSUE THREAD

**Issue by trezy** [fdgt-apis/api#53]
**Describe the bug**
The websocket reports the `api.fdgt.dev` cert when it should be reporting the `irc.fdgt.dev` cert.

**Additional context**

From Discord:
> I'm also running into some SNI issue with the websocket library when trying to add support for this, will try to resolve tomo com.neovisionaries.ws.client.HostnameUnverifiedException: The certificate of the peer (CN=api.fdgt.dev) does not match the expected hostname (irc.fdgt.dev) - @Prodigy

**Comment by iProdigy** [comment]
Can confirm that this has been fixed

**Comment by trezy** [comment]
Hey @all-contributors, please add @iProdigy for reporting bugs.
