### ISSUE TITLE
Bits without --message get a empty message

### ISSUE THREAD

**Issue by PhilippHeuer** [fdgt-apis/api#60]
**Describe the bug**
When you simulate a bits event and don't provide a message then the text will really be empty.
A cheer message always has to contain at least the used cheer emote.

It's not possible to cheer without a message as the generated event when using bits without --message.

**To Reproduce**
`bits --channel name --bitscount 100`

**Expected behavior**
The message has to contain at least a cheer emote -> ie. `Cheer100` - it can't be empty.

**Comment by trezy** [comment]
Yeah, that's a good call. I haven't put much thought into handling emotes with `fdgt` yet, but it's probably going to be a necessity. I'll start noodling on how best to implement this.
