### ISSUE TITLE
--giftcount flag not reflecting different numbers

### ISSUE THREAD

**Issue by opti21** [fdgt-apis/api#85]
**Describe the bug**
The --giftcount flag is not reflecting the numbers following after it.

**To Reproduce**
1.  Send the --giftcount flag with other numbers then the default 5
2. Userstate still shows that the user is gifting the default 5 

**Expected behavior**
It should reflect the given number after the --giftcount flag

**Screenshots**
![error screenshot](https://i.imgur.com/Cgp9ng4.png)

**Comment by iProdigy** [comment]
Using `--count` should work; the website seems to be out of date.

**Comment by opti21** [comment]
Ah gotcha, thank you that worked.

**Comment by trezy** [comment]
Yup, I'm working on fixing the site so it's always up-to-date, but we're not there yet. Thanks for helping, @iProdigy.
